### ISSUE TITLE
Hi there! I have some doubts about your article

### ISSUE THREAD

**Issue by tsq456** [petermekhaeil/petermekhaeil.com#2]
I used the method you mentioned in this [article](https://petermekhaeil.com/adding-dark-mode-to-your-tailwind-css-website/) on your blog. I can now successfully switch to dark-mode, but I found that when switching pages, the style will first become white and then quickly change to dark-mode. 

Do you have any solutions to this problem?

You can see my demo site here, https://610beea733a13bf0419dac88--determined-noether-276811.netlify.app/, and you can find the switcher in the top-left.

Looking forward to your answer!

**Comment by petermekhaeil** [comment]
Looks like the script is being loaded later after page rendering, that is why there is a white flicker.

Some options you could try:
1. Move the script up above the `<script>` tags that are located in your `<footer>`. So that your page can execute the script before it executes the other scripts that you are loading.
2. Move the script to the `<head>` to block the page rendering until it has been executed. It is a small script so I do not think it will block the rendering for too long. But it is worth a try.

Try either options and please let me know if it helps.

**Comment by tsq456** [comment]
Thanks for your reply!

I found that this problem was caused by the location of the script earlier, and I moved the following code to the head and before the css, and solved the problem.

``` js
<script>
    if (localStorage.getItem("theme") === "dark" || (!localStorage.getItem("theme") && window.matchMedia("(prefers-color-scheme: dark)"))) {
      document.querySelector('html').classList.add("dark");
    }
</script>
```

And I checked your code, the script is behind the footer, but your website does not have a similar problem.

**Comment by petermekhaeil** [comment]
Awesome! Good find.

My website does not have this problem because I have no other scripts running on the page. Thanks for the feedback, I can update the blog post to share this solution.

I'll close the issue, let me know again if the problem comes back.
